# Generated by Django 4.0.4 on 2022-06-24 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phoneNumber', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('message_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
